### ISSUE TITLE
parsing fails on MS Edge

### ISSUE THREAD

**Issue by Nirazul** [malyw/sass-to-js#4]
I've created a [Codepen](http://codepen.io/Nirazul/pen/mWZyOZ) to demonstrate the faulty behaviour.

The problem is that:
```js
window.getComputedStyle(
  document.querySelector('body'), '::before')
  .getPropertyValue('content');
```

...returns `none` for pseudo elements that don't exist.
Ideally, that never happens. But I think this is an enough usual use case to be handled by the library.

If you want I can try and prepare a PR to solve this issue.

**Comment by malyw** [comment]
I assume it's ok, that parsing fails for not existing element, which will signal about an improper attempt, instead of hiding that silently.
Can you provide your use case, just to make sure I'm not missing something.

**Comment by Nirazul** [comment]
I've stumbled upon the issue that javascript was loaded before the stylesheet was applied to the element. I figure, this happens when using `async` or `defer` keywords on script tags.

Curiously, this only happens on MS Edge where keywords are returned as `"none"` instead of `""`

**Comment by Nirazul** [comment]
I just realized that setting `debug` to `false` would be enough for me. It seems to work properly apart from the thrown error in the console :)

**Comment by malyw** [comment]
Yep, `debug: false;` should help.
It looks like the Chrome bug or at least the incompatibility between browsers.
Here I created an online test demo: http://codepen.io/malyw/pen/GWbBGX?editors=1010
And a bug for Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=709744

**Comment by Nirazul** [comment]
Ah, good to know that Chrome is wrong on that one. Thanks for filing the bug 👍
